### ISSUE TITLE
D1 retrospective meeting minutes

### ISSUE THREAD

**Issue by pangkaho14** [JustBrandonLim/ICT2106_P2_Project_M1#128]
A retrospective was held and the following is what is discussed by the team on:

1. What did the team do well?
2. What didn't go well?
3. What can be improved?

The following are what was discussed during the retrospective using starfish retrospective. The starfish retrospective helps to identify and prioritize the areas of improvement by considering five key aspects: what to keep doing, what to stop doing, what to start doing, what to do less of, and what to do more of.

Each comment by a team member summarizes the key points that each member felt.

**Comment by pangkaho14** [comment]
**D1 retrospective:**

Keep: The team appreciated the commitment, cooperation, and knowledge sharing among team members and wants to continue this positive aspect.

Stop: The team realized that they need to stop neglecting their project board and make sure to keep it updated and relevant to the project.

Start: The team wants to start prioritizing better and focusing more on the tasks that are essential to delivering value to the project, and also to establish better communication and structure with other teams in advance.

Less: The team wants to do less time-wasting activities and focus more on efficient time management within the team.

More: The team wants to do more to improve their communication and time management skills to ensure that the project runs smoothly and efficiently.

**Comment by pangkaho14** [comment]
I believe that the team needs to prioritize tasks better to focus on what delivers value to the project. In the next deliverable, I hope to see better prioritization of the tasks so that we complete the important tasks first. I think that we can improve our communication with other teams to ensure that everyone is working towards the same goals. I appreciate the team's commitment, cooperation, and knowledge sharing to help one another with different tasks and needs.

**Comment by ncmj1998** [comment]
Our team faced a challenging deadline that required us to work efficiently and collaboratively. While we were ultimately successful in completing the project on time and meeting all the requirements, we faced some challenges with documentation. Specifically, we found it difficult to keep track of all the information we needed to document due to time constraints. Despite this, we maintained a positive attitude and worked well together throughout the project, leveraging each other's strengths to overcome obstacles and achieve our goals. Looking forward, we could set earlier deadlines for individual tasks and create a more detailed project plan to help us stay on track.

**Comment by ShaunVSIT** [comment]
I believe that the team needs to stop neglecting the project board and keep it updated and relevant to the project. I think the team has done well to cooperate and help one another, but we need to be more focused and less playful during meetings so that we are more productive. We should also put a strong emphasis on keeping our documentation up-to-date so that it is not such a rush towards the end.

**Comment by fabianchua6** [comment]
The team should do less time-wasting activities and focus on better time management so that we can better meet the deadlines on time. The deadlines would also include documentation updates so that we do not neglect it. In our next deliverable, I want to see a stronger focus on setting deadlines for tasks and ensuring that we have enough time for documentation. I appreciate the team's cooperative and helpful attitude.

**Comment by fabianchua6** [comment]
Starfish Retrospect

![Image](https://user-images.githubusercontent.com/57614749/222885619-9eb56afc-10ae-4693-aa3b-3ff74dfb6945.png)
