### ISSUE TITLE
4.1.4 Implementation for Apply across application devices feature | Start: 03/03/23 | End:

### ISSUE THREAD

**Issue by bran-donut** [JustBrandonLim/ICT2106_P2_Project_M1#76]

**Comment by JustBrandonLim** [comment]
![Image](https://user-images.githubusercontent.com/93673724/227271735-2a22927f-a108-4167-96b1-f3bbce9ad232.png)

Implemented `ApplyDeviceConfigurationsSameTypeAsync` that allows us to apply config to all based on the device brand and device model (composite key in DB).


![Image](https://user-images.githubusercontent.com/93673724/227272683-071226d7-1a46-4376-8ffd-36462385beaa.png)

Implemented `ApplyDeviceConfigurationsSameType` in the controller, so that the frontend can call the function.

**Comment by p1816246** [comment]
![Image](https://user-images.githubusercontent.com/39515771/227475657-8571120c-51b5-4654-b3bc-9ab21e304429.png)

Implemented UI for Apply across application devices feature 

![Image](https://user-images.githubusercontent.com/39515771/227476716-538f51b4-9d51-4c55-989b-a4fbb053c739.png)

Implemented function to call API

**Comment by JustBrandonLim** [comment]
![Image](https://user-images.githubusercontent.com/93673724/227586083-373b1dc0-10a7-476e-af2d-7c2021fe7594.png)

Fixed the bug for not being able to update device configuration properly when applying to all.

There was a typo in the code where it was still setting the same deviceId as the original one.
